import pytest


@pytest.fixture(scope="module")
def expected_search_all_function_one_file():
    return {
        'RegexSearcher': [{'line_number': 32,
                           'final_result_line_string': './tests/test_files/example_file_1.txt > line 32: The script 01should be compatible with Python 2.7, and in line script with PEP8 coding guidelines.',
                           'file_name': './tests/test_files/example_file_1.txt', 'match_string_pos': 11,
                           'matching_string': '01',
                           'line_string': 'The script 01should be compatible with Python 2.7, and in line script with PEP8 coding guidelines.'},
                          {'line_number': 34,
                           'final_result_line_string': './tests/test_files/example_file_1.txt > line 34: Add a few automated functional 01tests to your script (testing framework of your choice).',
                           'file_name': './tests/test_files/example_file_1.txt', 'match_string_pos': 31,
                           'matching_string': '01',
                           'line_string': 'Add a few automated functional 01tests to your script (testing framework of your choice).'},
                          {'line_number': 38,
                           'final_result_line_string': './tests/test_files/example_file_1.txt > line 38:  01',
                           'file_name': './tests/test_files/example_file_1.txt', 'match_string_pos': 1,
                           'matching_string': '01', 'line_string': ' 01'}],
        'RegexSearcherUnderscore': [{'line_number': 32,
                                     'final_result_line_string': './tests/test_files/example_file_1.txt > line 32: The script 01should be compatible with Python 2.7, and in line script with PEP8 coding guidelines.\r\n                                                            ^^',
                                     'file_name': './tests/test_files/example_file_1.txt', 'match_string_pos': 11,
                                     'matching_string': '01',
                                     'line_string': 'The script 01should be compatible with Python 2.7, and in line script with PEP8 coding guidelines.'},
                                    {'line_number': 34,
                                     'final_result_line_string': './tests/test_files/example_file_1.txt > line 34: Add a few automated functional 01tests to your script (testing framework of your choice).\r\n                                                                                ^^',
                                     'file_name': './tests/test_files/example_file_1.txt', 'match_string_pos': 31,
                                     'matching_string': '01',
                                     'line_string': 'Add a few automated functional 01tests to your script (testing framework of your choice).'},
                                    {'line_number': 38,
                                     'final_result_line_string': './tests/test_files/example_file_1.txt > line 38:  01\r\n                                                  ^^',
                                     'file_name': './tests/test_files/example_file_1.txt', 'match_string_pos': 1,
                                     'matching_string': '01',
                                     'line_string': ' 01'}],
        'RegexSearcherColor': [{'line_number': 32,
                                'final_result_line_string': './tests/test_files/example_file_1.txt > line 32: The script \x1b[31m01\x1b[mshould be compatible with Python 2.7, and in line script with PEP8 coding guidelines.',
                                'file_name': './tests/test_files/example_file_1.txt', 'match_string_pos': 11,
                                'matching_string': '01',
                                'line_string': 'The script \x1b[31m01\x1b[mshould be compatible with Python 2.7, and in line script with PEP8 coding guidelines.'},
                               {'line_number': 34,
                                'final_result_line_string': './tests/test_files/example_file_1.txt > line 34: Add a few automated functional \x1b[31m01\x1b[mtests to your script (testing framework of your choice).',
                                'file_name': './tests/test_files/example_file_1.txt', 'match_string_pos': 31,
                                'matching_string': '01',
                                'line_string': 'Add a few automated functional \x1b[31m01\x1b[mtests to your script (testing framework of your choice).'},
                               {'line_number': 38,
                                'final_result_line_string': './tests/test_files/example_file_1.txt > line 38:  \x1b[31m01\x1b[m',
                                'file_name': './tests/test_files/example_file_1.txt', 'match_string_pos': 1,
                                'matching_string': '01', 'line_string': ' \x1b[31m01\x1b[m'}],
        'RegexSearcherMachine': [{'line_number': 32,
                                  'final_result_line_string': './tests/test_files/example_file_1.txt:32:11:The script 01should be compatible with Python 2.7, and in line script with PEP8 coding guidelines.',
                                  'file_name': './tests/test_files/example_file_1.txt', 'match_string_pos': 11,
                                  'matching_string': '01',
                                  'line_string': 'The script 01should be compatible with Python 2.7, and in line script with PEP8 coding guidelines.'},
                                 {'line_number': 34,
                                  'final_result_line_string': './tests/test_files/example_file_1.txt:34:31:Add a few automated functional 01tests to your script (testing framework of your choice).',
                                  'file_name': './tests/test_files/example_file_1.txt', 'match_string_pos': 31,
                                  'matching_string': '01',
                                  'line_string': 'Add a few automated functional 01tests to your script (testing framework of your choice).'},
                                 {'line_number': 38,
                                  'final_result_line_string': './tests/test_files/example_file_1.txt:38:1: 01',
                                  'file_name': './tests/test_files/example_file_1.txt', 'match_string_pos': 1,
                                  'matching_string': '01', 'line_string': ' 01'}]
    }
